apiVersion: v1
kind: Service
metadata:
  name: go-test-service
spec:
  selector:
    app: go-test
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080 #11 port accessible from outside the cluster
  #type: LoadBalancer  
  #type: ClusterIP  
  type: NodePort #11 with nodPort param in ports